.qawolf/responsive.test.ts, ui/src/primitives/box/box.stories.tsx
* Add a storybook entry for a box element we can test with
* Add a QAwolf test for making sure the `display` css property is set correctly based on the React props
We'd like to take the breakpoints directly from the `studioTheme` since it can vary based on how the theme evolves. However that lead us into some import trouble.
Appreciate some tips there if there's an easy way to fix that!
=> [qa] Add test for Box breakpoints

.qawolf/responsive.test.ts, ui/src/components/autocomplete/autocomplete.qa.ts, ui/src/components/dialog/dialog.qa.ts, ui/src/components/menu/menuButton.qa.ts, ui/src/components/tab/tab.qa.ts, ui/src/primitives/box/box.qa.ts
This fixes an issue that reported inaccurate error message if something failed during `beforeAll`: E.g. if launching `qawolf` in the `beforeAll`-callback failed, the `browser` variable would be undefined, which again would make the `afterAll` callback fail when it tried to call `close()` on it. This obscured the original error, and made jest report `TypeError: Cannot read property 'close' of undefined` as the error and not the original error that happened in the beforeAll`-callback.
Note: added a few non-null assertions in the actual tests, since we can be sure that the variables are initialized when if we get to actually running the test.
=> [chore] Ensure accurate error reporting if beforeAll callback fails

ui/src/primitives/heading/heading.stories.tsx, ui/src/primitives/heading/heading.tsx, ui/src/primitives/label/label.stories.tsx, ui/src/primitives/label/label.tsx, ui/src/primitives/text/text.stories.tsx, ui/src/primitives/text/text.tsx
This change adds a `textOverflow` property to the typographic primitives `Heading`, `Label`, and `Text`. This means you can do the following to achieve a single line of text which is concatenated with `…`:
```jsx
<Text textOverflow="ellipsis">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</Text>
```
Which will render:
=> [ui] Add `textOverflow` property to Heading, Label and Text

ui/src/components/dialog/dialog.stories.tsx, ui/src/components/dialog/dialog.tsx
- This change introduces a new `onClickOutside` property to the `Dialog` component.
- This change is introduced because in some cases the click outside behavior must be optional.
- Create a Dialog instance without a `onClickOutside` property and make sure the Dialog is not closed when clicking outside of the Dialog.
- Create a Dialog instance​ with a `onClickOutside` property and make sure the callback is called when clicking outside of the Dialog.
- Adds a new `onClickOutside` property to `Dialog` for handling cases when there's need to trigger changes when clicking outside of the dialog.
**BREAKING CHANGE**: The `onClose` callback is no longer called when the user clicks outside of the `Dialog` component, since there's now a designated callback for that.
=> [ui] Prevent Dialog from closing on click outside

ui/src/components/autocomplete/autocomplete.stories.tsx, ui/src/components/autocomplete/autocomplete.tsx
This change makes the open button correctly inherit padding and font size within the `Autocomplete` component.
- Open the [`Autocomplete` component in Storybook](https://sanity-ui-storybook-git-bug-ch5877fix-autocomplete-open-button.sanity.build/?path=/story/components-autocomplete--default)
- Change the `padding` and `fontSize` properties
- Make sure the padding and font size of the open button (with chevron) is matching the input field.
=> Fix padding and font size of Autocomplete’s open button

.cypress/integration/ui/layer.spec.ts, ui/src/components/dialog/dialog.stories.tsx, ui/src/components/dialog/dialog.tsx, ui/src/components/dialog/dialogContext.ts, ui/src/components/dialog/dialogProvider.tsx, ui/src/components/dialog/index.ts, ui/src/components/dialog/useDialog.ts, ui/src/components/toast/toastProvider.tsx, ui/src/hooks/index.ts, ui/src/hooks/useMediaIndex.stories.tsx, ui/src/hooks/useMediaIndex.ts, ui/src/utils/layer/layer.stories.tsx, ui/src/utils/layer/layer.tsx, ui/src/utils/layer/layerProvider.tsx
This change adds support for responsive z-offsets:
```tsx
// This layer will have z-index 0 on mobile, 1 on tablet, and 2 on desktop:
<Layer zOffset={[0, 10, 20]}>Test layer</Layer>
```
This change also introduces a new component called `DialogProvider` that can be used to provide default `zOffset` and `position` to nested `Dialog` components:
```tsx
<DialogProvider position="absolute" zOffset={100}>
<Dialog id="dialog-a">This dialog will get z-index 100</Dialog>
<Dialog id="dialog-a">This dialog will get z-index 100</Dialog>
</DialogProvider>
```
=> feat(ui): add support for responsive z-offsets and `DialogProvider` for defaults

docs/screens/arcade/arcade.tsx
I was playing around with the Arcade and noticed it fires requests at every keystroke. That's because the usage of Next's router.replace doesn't include a `shallow: true` option.
If we add that, Next won't try to query the backend every time the router changes, which will improve performance of the query encoding mechanism and save a lot of requests from being made. [More on Next's docs](https://nextjs.org/docs/routing/shallow-routing).
=> fix(docs): add `shallow: true` to query changes in arcade

ui/src/hooks/useMediaIndex.ts
- Adds support for older mediaQuery syntax
- Fixes https://github.com/sanity-io/design/issues/566
I tested this in the local storybook with `dev:ui`. When viewing the `useMediaIndex` entry, it was initially broken, but this change fixed it.
I'm unable to test in my local studio (using `yarn link @sanity/ui`) because of some Styled Components issues.
- Adds support for Safari 13
=> fix(ui): fix `useMediaIndex` browser support issue (Safari 13)

ui/src/components/toast/toast.tsx
Adds the role attribute to the toast primitive, in order to enable screen readers to announce the message.
Trigger a toast message with screen reader enabled, and the message should be announced.
=> feat(ui): add role attribute to toast

packages/@sanity/ui/src/components/dialog/dialog.tsx, packages/@sanity/ui/src/components/dialog/dialog.workshop.tsx
This update is introduced as we have encountered situations in the studio where we need to hide the close button.
- Adds a `__unstable_hideCloseButton` prop to the `Dialog`.
- Conditionally renders close button depending on the `__unstable_hideCloseButton` value, and whether `onClose` is passed or not.
If `onClose` is passed and `__unstable_hideCloseButton` is `true`, the close button should not be rendered.
```
<Dialog onClose={handleClose} __unstable_hideCloseButton>
{/* content */}
</Dialog>
```
If `onClick` is not passed, the close button should not be rendered.
```
<Dialog>
{/* content */}
</Dialog>
```
- Add `__unstable_hideCloseButton` property to `Dialog` to hide close button
=> feat(ui): add option to hide `Dialog` close button

.cypress/integration/ui/dialog.spec.ts, packages/@sanity/ui/src/components/dialog/__workshop__/autoFocus.tsx, packages/@sanity/ui/src/components/dialog/dialog.tsx
This change fixes an issue which was caused by not including the dialog header as a container of focusable elements within dialogs. Closes #967.
=> fix(ui): focus the first focusable element in dialogs

packages/@sanity/ui/src/components/menu/menuItem.tsx
Fixes issue where when using the MenuItem as an anchor wasn't giving the right style
Changing any of the MenuItem examples to be `as="a"` and making it disabled, before the fix, shows that while it is disabled the styles do not reflect that.
Fix visual bug when a disabled MenuItem was used as an anchor
=> fix(MenuItem): add data-disabled to MenuItem when it is disabled

apps/docs/components/article/articleContent/blocks/codeExample/codeExample.tsx, apps/docs/pages/arcade-frame.tsx
This adds support for styled-components in Arcade, inside of the Hook tab.
What should we call the Hook tab since it is the functional component's scope?
- Add support of styled-components
=> feat(docs): add suppport for styled-components in arcade

apps/docs/lib/nav/nav.ts, apps/docs/lib/page/_global/loadGlobalPageData.ts, apps/docs/lib/page/docs/loadDocsPageData.ts, apps/docs/package.json, apps/docs/screens/arcade/arcade.tsx, packages/@sanity/ui/package.json, packages/@sanity/ui/src/hooks/_internal/useUnique.ts, yarn.lock
This PR drops the use of `lodash` in `@sanity/ui`, since it was only used for `isEqual` in one place for a very specific use case with the portal implementation, where the comparison was a record of DOM elements - these can be triple-equally checked instead.
This cuts the bundle size for anyone using `@sanity/ui`.
I also took a stab at removing it from the rest of the repo, but stopped when I found `debounce` being used. It's not critical that we replace it in every instance, but it does add a bit of weight. To help tree shaking, I replaced `lodash` with `lodash-es` in the `docs` app.
- That the changes makes sense and does not have any outside impact I am unaware of
- Removed `lodash` as a dependency
=> refactor(ui): use simpler `isEqual` for `useUnique` hook

packages/@sanity/ui-workshop/src/main/workshopNavbar.tsx
This PR adds a button in the workshop navbar that makes it possible to open a story in a new window. Sometimes it's nice, and necessary, to be able to work with a story outside of the workshop framework especially when it comes to responsive design.
n/a
Add button in the workshop navbar that makes it possible to open a story in a new window
=> feat(ui-workshop): add open story in new window 

packages/@sanity/ui/src/utils/errorBoundary.tsx
Ran into a small bug with the error boundary.
If some component in the tree throws something and `error.message` is not a string, it ends up throwing again within the error boundary's render. ~I also changed the type of `error` to any in this case because it possible to throw non-errors and have them bubble here.~ I reverted that since it seemed to cause some type friction.
Do the changes makes sense? Are the types correct?
Fixes an issue where the `ErrorBoundary` itself could error if the `error.message` was not a string.
=> fix(ui): check if error.message is a string before rendering

packages/@sanity/icons/package.json, packages/@sanity/logos/package.json, packages/@sanity/ui/package.json
React 18 is out and we're already seeing support requests because of npms strict peer dependency handling. This PR upgrades the supported peer dependency range to include React 18, as all of the packages should be compatible with it.
=> chore: mark packages as React 18-compatible

packages/@sanity/ui/src/primitives/tooltip/tooltip.tsx
Not quite sure _why_, but when using the tooltip inside of Sanity (on the publish button, specifically), it now crashes with an error: `flushSync() was called from inside a lifecycle method`. It might be that this forcing is no longer necessary due to upstream changes in popper.js, but I noticed that the popover component has a try/catch around the `forceUpdate()` call, and figured doing the same here would be acceptable for now - might warrant a deeper look at what is going on, but this unblocks us for now.
- That the code change makes sense and does not have unintended side effects
- Fixed an issue where the tooltip component might crash with a `flushSync()` error
=> fix(ui): catch error when force updating tooltip popper

packages/@sanity/logos/src/sanityLogo.tsx
When using `<SanityLogo dark />`, a warning is printed from React because `dark` is not a property on `<svg>`. This is caused by spreading all the props from `SanityLogo` onto `svg`.
This PR fixes this by destructuring the props and removing `dark` before spreading the other props onto the SVG element.
- Fixed warning when using `dark` prop on `SanityLogo`
=> fix(logos): do not pass `dark` prop on to SVG element

apps/docs/components/article/articleContent/blocks/groqLogoGrid.tsx, apps/docs/components/article/articleContent/blocks/sanityLogoGrid.tsx, apps/docs/components/article/articleContent/logoGrid/logoGrid.tsx, examples/studio/src/$sanity/dashboard/plugin.ts, packages/@sanity/ui-workshop/src/inspector/WorkshopInspector.tsx, packages/@sanity/ui-workshop/src/plugins/perf/hooks/usePerfTest.tsx, packages/@sanity/ui-workshop/src/types/core.ts, packages/@sanity/ui-workshop/src/types/plugin.ts, packages/@sanity/ui/src/components/autocomplete/autocomplete.tsx, packages/@sanity/ui/src/components/menu/menuGroup.tsx, packages/@sanity/ui/src/components/menu/menuItem.tsx, packages/@sanity/ui/src/components/tab/tab.tsx, packages/@sanity/ui/src/components/tree/treeItem.tsx, packages/@sanity/ui/src/primitives/button/button.tsx, packages/@sanity/ui/src/primitives/textInput/textInput.tsx
Relates to  #990 and #3612. The `ComponentType` usage is blocking adoption of `@sanity/ui@next` on `react@18`. The reason is `ComponentType` is no longer assignable to `ReactNode`. The fix is to use `ElementType` instead.
=> fix: replace `ComponentType` with `ElementType`

packages/@sanity/logos/package.json
This is what's causing the `cannot use import statement outside a module` currently [happening on the react 18 branch](https://github.com/sanity-io/sanity/actions/runs/3056551512/jobs/4930830587).
=> fix: wrong file extension on main field

packages/@sanity/ui/src/__workshop__/constants.ts, packages/@sanity/ui/src/primitives/textInput/textInput.tsx
Adds the ability to use the `color` type on a `TextInput` component, which allows for rendering of `<input type="color">` ([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color)).
Even though this is only a small TypeScript change, it's worth reviewing whether this type is desirable for the `TextInput` component. I think it is :)
The color input type can be tested in the Workshop under `Primitives > TextInput > Typed`. Alternatively, here is a slightly more elaborate example, using Sanity v3:
```typescript
import React, {ForwardedRef} from 'react'
import {PatchEvent, set} from 'sanity/form'
import {TextInput as _TextInput} from '@sanity/ui'
import {ObjectSchemaType} from '@sanity/types'
import debounce from 'lodash/debounce'
import styled from 'styled-components' …
```
=> Add 'color' type to TextInput component

src/primitives/textInput/textInput.tsx
Simply adds an accessible `aria-label` to the `TextInput` component's clear button, similar to what's on `Autocomplete`. That's it!
=> fix(a11y): add `aria-label` to `TextInput` clear button

src/primitives/code/styles.ts, src/primitives/heading/styles.ts, src/primitives/label/styles.ts, src/primitives/text/styles.ts
This fix allows removing ugly workarounds like: https://github.com/sanity-io/next-sanity/pull/232
And still have the right SVG alignment:
Without this fix, libraries like `next-sanity` has to use ugly CSS workarounds to avoid this outcome on projects that uses Tailwind:
=> fix: apply display: inline to SVGs to be tailwind compatible

package.json, pnpm-lock.yaml, renovate.json
This PR re-pins `@floating-ui/react-dom` to `1.1.1` (originally added in 1eb56ef3411cc72ae9096aa3a20c3e5cc7b76602)
It also adds it to renovate's ignore list, so it hopefully shouldn't be automatically overridden in future.
As a reminder: we currently pin to this version to avoid placement issues with `<Popover>` content when `open` is true on mount.
=> fix: re-pin `@floating-ui/react-dom` to `1.1.1`

src/primitives/_selectable/style.ts, src/primitives/button/styles.ts, src/primitives/card/styles.ts
This PR enables hover styles for `<Button>`, `<Card>` and _selectable_ components (`<MenuGroup>`, `<MenuItem>`) to be displayed when `data-hovered` is set. This is similar to how `data-selected` works on these components.
Also similar to `data-selected`, the presence of `data-disabled` will override this behaviour, and these styles will also not be displayed if no hover support is detected.
This is in service of command lists in the studio that want to ergonomically set hover state on list items when navigating via the keyboard (e.g. global search).
Setting `data-hovered` on any of the above components should display their hover styles.
=> feat: allow hovered styles to be applied via the `data-hovered` attr
